### ISSUE TITLE
"VOIP" and "UNKNOWN" are inverted when customizing node distributions

### ISSUE THREAD

**Issue by gregs5** [CyberReboot/gensynet#6]
Just ran into this today when generating a data set.  When it first generates totals and then prompts you to reset the distribution you see:
...
VOIP phone : 0
Unknown : 160
Manually reset the above Device Role Distribution? [No]: yes

...but then it presents "Unknown" before "VOIP" which through me off:
Unknown (MAX=191) [160]: 
VOIP phone (MAX=31) [0]: 31

Can we make these uniform?

**Comment by lilchurro** [comment]
I think I forgot to update this... Commit 528f706a actually fixed it by sorting the list prior to printout.
